### ISSUE TITLE
Feature request: switch between hexdump and text only

### ISSUE THREAD

**Issue by demothorg** [stef-levesque/vscode-hexdump#19]
It is very useful feature, because text only mode are convenient for navigation. For example:
1. Look for some string in binary,
2. Switch to hex mode for research the area.

Most popular hex editors supports this (hiew, hex workshop, 010 editor).

**Comment by stef-levesque** [comment]
Maybe I'm missing the point here :)

You can open any text file regularly with VSCode, and it will display it as text.
You can also view the ASCII values on the right section.

Although, I know that the default `Search` command is not that useful, since the text will often be broken into lines...

I could probably add a new command in the extension, something like `Ascii Search`, that would move the cursor to the next location of the occurence.

**Comment by stef-levesque** [comment]
`Search string` implemented in version 1.2.0

**Comment by demothorg** [comment]
If VS Code could open a binary file in text mode, it would be great to be able to switch from current text position to hex mode with the same position. But VS Code cannot...

Thanks for search string, it is very useful feature.
