### ISSUE TITLE
Hexdump isn't working on VSCode 1.11.1 on Ubuntu

### ISSUE THREAD

**Issue by derekmulcahy** [stef-levesque/vscode-hexdump#24]
Hi,

I upgraded to VSCode 1.11.1 and hexdump has stopped working on Ubuntu. I click on the hexdump icon for a file or select Show Hexdump from the file menu and nothing happens. It used to work fine before I upgraded. Hexdump in VSCode 1.11.1 works on OS X 10.12.4.

Is there anything I can do to produce more useful debug to help you track it down?

Thanks,
Derek

**Comment by stef-levesque** [comment]
Unfortunately, I didn't made logs in that extension :( but it's on the TODO list.

Are those file especially large? I did encounter large file that would behave differently on Mac or Windows (my main test platforms). You could try to lower `hexdump.sizeWarning` in your settings, to see if the warning still display. Reducing `hexdump.maxLineCount` could also help, if the problem comes from the Editor timing-out on the file opening.

**Comment by derekmulcahy** [comment]
It fails even with small files. I reduced the warning size and then I get the warning but still no hexdump output. Does it have any external dependencies?

**Comment by derekmulcahy** [comment]
I ran vscode again in verbose mode and it claims to be out of space when trying to run hexdump (ENOSPC, see attached log) but I have 8G of space in the only filesystem. Odd!

[hexdump.txt](https://github.com/stef-levesque/vscode-hexdump/files/907893/hexdump.txt)

**Comment by derekmulcahy** [comment]
OK, I found a solution. According to this

https://code.visualstudio.com/docs/setup/linux#_updates

Vscode runs the system out of notification slots. Ubuntu was configured for just 8192, I increased it to 32768 and all is well.

Thanks for playing :-)

**Comment by stef-levesque** [comment]
Quite the investigation! Thanks for the info :)
