### ISSUE TITLE
opening extra large file - feature request

### ISSUE THREAD

**Issue by raxim1** [stef-levesque/vscode-hexdump#34]
I think it has been raised once. My problem under ubuntu is very hard to find good hexeditor.
I found one is the GHex, but i would like to use somehow this one. I don't like to install hundreds of independent apps.

I know there is some limitation on extra large file, but for example in eclipse to write a plugin which read only buffers is very easy 20 lines code. Even in javascript it's just one line. (FileReaderSync under WebWorker)

extra large file means 40GB :)

I tried to force to open, clicking on the file header again, but it does not do anything.

Even on small 57KB size, the file won't be displayed because of the encoding, if it's binary somehow this plugin should be triggered as default binary editor.

**Comment by stef-levesque** [comment]
Version 1.6.0 should better handle large files. You can try to adgjust `hexdump.sizeDisplay`for your needs, but due to a VSCode limitation, the color syntax won't work past 5Mb or so.

As for triggering the extension as default for binary files. there is already an issue/feature request on VSCode for that (see microsoft/vscode#12176)
But there is not much traction on this.
